// <auto-generated />
namespace AspNetFSharp.Migrations
open AspNetFSharp.DataStore;
open Microsoft.EntityFrameworkCore;
open Microsoft.EntityFrameworkCore.Infrastructure;
open Microsoft.EntityFrameworkCore.Metadata;


[<DbContext(typeof<CityInfoContext>)>]
type CityInfoContextModelSnapshot=
    inherit ModelSnapshot

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
        |> ignore

        modelBuilder.Entity("AspNetFSharp.Entities.City", fun b ->
                b.Property<int>("Id").ValueGeneratedOnAdd() |> ignore
                b.Property<string>("Description") |> ignore
                b.Property<string>("Name") |> ignore
                b.HasKey("Id") |> ignore
                b.ToTable("Cities") |> ignore
            )
        |> ignore

        modelBuilder.Entity("AspNetFSharp.Entities.PointOfInterest", fun b ->
                b.Property<int>("Id").ValueGeneratedOnAdd() |> ignore
                b.Property<int>("CityId") |> ignore
                b.Property<string>("Description") |> ignore
                b.Property<string>("Name") |> ignore
                b.HasKey("Id") |> ignore
                b.HasIndex("CityId") |> ignore
                b.ToTable("PointsOfInterest") |> ignore
            ) |> ignore

        modelBuilder.Entity("AspNetFSharp.Entities.PointOfInterest", fun b ->
                b.HasOne("AspNetFSharp.Entities.City", "City")
                    .WithMany("PointsOfInterest")
                    .HasForeignKey("CityId")
                    .OnDelete(DeleteBehavior.Cascade) |> ignore
            ) |> ignore

